apiVersion: apps/v1
kind: Deployment
metadata:
  name: pulse-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pulse
  template:
    metadata:
      labels:
        app: pulse
    spec:
      initContainers:
        - name: run-migrations
          image: moabdelazem/pulse:latest
          command: ["/nodejs/bin/node", "dist/db/migrate.js"]
          envFrom:
            - secretRef:
                name: pulse-database-secret
      containers:
        - name: pulse
          image: moabdelazem/pulse:latest
          ports:
            - containerPort: 8585
          envFrom:
            - configMapRef:
                name: pulse-configmap
            - secretRef:
                name: pulse-database-secret
          resources:
            limits:
              memory: "512Mi"
              cpu: "256m"
            requests:
              memory: "256Mi"
              cpu: "128m"
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8585
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/health
              port: 8585
            initialDelaySeconds: 5
            periodSeconds: 10
      