apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - configmap.yaml
  - secret.yaml
  - statefulset.yaml
  - svc.yaml

commonLabels:
  app.kubernetes.io/name: pulse
  app.kubernetes.io/managed-by: kustomize
