apiVersion: v1
kind: Secret
metadata:
  name: pulse-database-secret
stringData:
  DATABASE_URL: postgresql://devuser:devpass@pulse-database-svc:5432/devdb
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
stringData:
  POSTGRES_USER: devuser
  POSTGRES_PASSWORD: devpass
  POSTGRES_DB: devdb